services:
  db:
    image: postgres:17
    container_name: macer_db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: macer_web
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    # command: >
    #   sh -c "
    #   python manage.py migrate &&
    #   python manage.py migrate keyboardApp --database=keyboardAppDB &&
    #   python manage.py collectstatic --noinput &&
    #   gunicorn src.wsgi:application --bind 0.0.0.0:8000 --timeout 120
    #   "
    # command: >
    #   sh -c "
    #   python manage.py migrate &&
    #   python manage.py migrate keyboardApp --database=keyboardAppDB &&
    #   python manage.py collectstatic --noinput &&
    #   gunicorn src.wsgi:application --bind 0.0.0.0:8000 --timeout 120 --workers 3
    #   "

    command: >
      sh -c "
      echo 'Waiting for DB...' &&
      while ! python -c \"import psycopg2; psycopg2.connect('host=db port=5432 dbname=$POSTGRES_DB user=$POSTGRES_USER password=$POSTGRES_PASSWORD')\" 2>/dev/null; do
        sleep 1;
      done &&
      python manage.py migrate &&
      python manage.py migrate keyboardApp --database=keyboardAppDB &&
      python manage.py collectstatic --noinput &&
      gunicorn src.wsgi:application --bind 0.0.0.0:8000 --timeout 120 --workers 3
      "
volumes:
  postgres_data:
