# Generated by Django 5.1.4 on 2025-01-12 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keyboardApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='price',
        ),
    ]
