# Generated by Django 5.1.4 on 2025-01-12 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyboardApp', '0002_remove_transaction_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bought_by', to='keyboardApp.store_item'),
        ),
    ]
