# Generated by Django 5.1.4 on 2025-01-12 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyboardApp', '0003_alter_transaction_item_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='store_item',
            name='item_description',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='store_item',
            name='item_key_color',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AlterField(
            model_name='store_item',
            name='item_name',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AlterField(
            model_name='store_item',
            name='item_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
