# Generated by Django 5.1.4 on 2025-01-12 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyboardApp', '0004_store_item_item_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='user_balance',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
