# Generated by Django 5.1.4 on 2025-01-13 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyboardApp', '0005_alter_user_info_user_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload_img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_img', models.CharField(max_length=50)),
                ('img_value', models.TextField()),
            ],
        ),
    ]
