# Generated by Django 5.1.4 on 2025-01-13 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keyboardApp', '0006_upload_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Upload_img',
        ),
    ]
