# Generated by Django 5.1.4 on 2025-01-14 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keyboardApp', '0007_delete_upload_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_user_id',
            new_name='transaction_user',
        ),
    ]
