# Generated by Django 5.1.4 on 2025-01-14 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keyboardApp', '0008_rename_transaction_user_id_transaction_transaction_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='item_id',
            new_name='item',
        ),
    ]
