# Generated by Django 5.1.4 on 2025-01-20 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyboardApp', '0009_rename_item_id_transaction_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='store_item',
            name='item_brand',
            field=models.CharField(default='N/A', max_length=50),
        ),
    ]
