# Generated by Django 5.1.4 on 2025-01-21 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyboardApp', '0010_store_item_item_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store_item',
            name='item_name',
            field=models.CharField(default='N/A', max_length=50, unique=True),
        ),
    ]
