# Generated by Django 5.1.4 on 2025-02-24 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyboardApp', '0012_alter_user_info_user_balance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='discount_code',
            fields=[
                ('discount_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.TextField(unique=True)),
                ('discount_percentage', models.IntegerField()),
                ('valid_from', models.DateTimeField(auto_now_add=True)),
                ('valid_to', models.DateTimeField()),
                ('is_activate', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='reviews',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('review_text', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('store_item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_review_item', to='keyboardApp.store_item')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_review', to='keyboardApp.user_info')),
            ],
        ),
    ]
