# Generated by Django 5.1.4 on 2025-03-17 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyboardApp', '0014_transaction_transaction_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
