# Generated by Django 5.1.4 on 2025-03-19 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keyboardApp', '0015_alter_transaction_transaction_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_date',
            new_name='transaction_date_temp',
        ),
    ]
