# Generated by Django 5.1.4 on 2025-03-19 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keyboardApp', '0016_rename_transaction_date_transaction_transaction_date_temp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_date_temp',
            new_name='transaction_date',
        ),
    ]
