# Generated by Django 5.1.4 on 2025-03-20 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyboardApp', '0017_rename_transaction_date_temp_transaction_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='user_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
