# Generated by Django 5.1.4 on 2025-03-22 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyboardApp', '0018_alter_user_info_user_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='review_text',
            field=models.TextField(default='N/A'),
        ),
    ]
