# Generated by Django 5.1.4 on 2025-03-22 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyboardApp', '0019_alter_reviews_review_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='reviewed_flag',
            field=models.IntegerField(default=0),
        ),
    ]
