# Generated by Django 5.2.4 on 2025-07-15 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyboardApp', '0020_transaction_reviewed_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='store_item',
            name='item_image',
            field=models.ImageField(blank=True, null=True, upload_to='img/keyboardImg'),
        ),
        migrations.AddField(
            model_name='user_info',
            name='user_role',
            field=models.CharField(default='user', max_length=30),
        ),
    ]
