# Generated by Django 5.2.4 on 2025-07-15 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyboardApp', '0021_store_item_item_image_user_info_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store_item',
            name='item_image',
            field=models.ImageField(blank=True, null=True, upload_to='keyboardApp/static/img/keyboardImg/'),
        ),
    ]
