name: CI

on:
  push:
    branches:
      - main
      - uat

  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Build Docker Image
        run: |
          docker build -t macer .

      - name: Run Django Checks
        run: |
          python manage.py check
